# This file was generated by GoReleaser. DO NOT EDIT.
cask "archivist" do
  version "0.2.16"

  on_macos do
    sha256 "1c02880854276d009e91f007d552923f6420747d20eda65ff9efa0d29ce6b8ab"
    url "https://github.com/mosaicss/archivist/releases/download/v#{version}/archivist_v#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "efcf889494911fbd98c3afe05c74b9e4a09de1052aa60376d6370d7be41ae909"
      url "https://github.com/mosaicss/archivist/releases/download/v#{version}/archivist_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1673ac76c8357092048139307d8fad05c4407553df250528ae3fd81b295cdd30"
      url "https://github.com/mosaicss/archivist/releases/download/v#{version}/archivist_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "archivist"
  desc "Archivist CLI for Mosaic filings research"
  homepage "https://mosaic-finance.com/products/archivist-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "archivist"

  postflight do
    # Strip the Gatekeeper quarantine flag. Release binaries are
    # unsigned until the operator provisions Apple notarization
    # (RELEASE_OPS_36_11.md section 2). macOS only: Homebrew >= 4.5
    # installs casks with Linux binaries on Linux too, where
    # /usr/bin/xattr does not exist and would abort the install.
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/archivist"]
    end
    # Fetch the matching Claude skill bundle when ~/.claude/skills
    # exists (same semantics as the pre-cask formula post_install).
    if File.directory?(File.expand_path("~/.claude/skills"))
      skill_dir = File.expand_path("~/.claude/skills/archivist")
      FileUtils.mkdir_p skill_dir
      system_command "/usr/bin/curl",
                     args: ["-fsSL", "-o", "/tmp/archivist-skill.tar.gz",
                            "https://github.com/mosaicss/archivist/releases/download/v#{version}/archivist_v#{version}_skill-bundle.tar.gz"]
      system_command "/usr/bin/tar",
                     args: ["-xzf", "/tmp/archivist-skill.tar.gz", "-C", skill_dir]
      FileUtils.rm_f "/tmp/archivist-skill.tar.gz"
    end
    # Stamp the install channel so `archivist update` routes users to
    # `brew upgrade` instead of self-replacing the binary.
    FileUtils.mkdir_p File.expand_path("~/.archivist")
    File.write File.expand_path("~/.archivist/install-channel"), "brew\n"
  end

  # No zap stanza required

end
